### ISSUE TITLE
it have stopped working for some reason

### ISSUE THREAD

**Issue by mpixelz** [Jeroen-G/Flickr#3]
Hi,
Ive been using this package for some time now.. and it was working just fine.. today i did php artisan cache:clear and the api stopped working.

ive dd'ed the result and it says:

```
Response {#601 ▼
  #contents: array:3 [▼
    "stat" => "fail"
    "code" => 100
    "message" => "Invalid API Key (Key has invalid format)"
  ]
}
```

but i have checked the flickr app garden and confirmed the api keys i have in my settings.
here is my controller:

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;

class WelcomeController extends Controller
{
    public function index(Request $request)
    {
        $flickr = new \JeroenG\Flickr\Flickr(new \JeroenG\Flickr\Api(env('FLICKR_KEY', ''), 'php_serial'));
        $perPage = 6;
        if ($request->has('page')) {
            $page = $request->has('page');
        } else {
            $page = 1;
        }
        $results = $flickr->listSets([
            'user_id' => env('FLICKR_USER'),
            'page' => $page,
            'per_page' => $perPage
        ]);
        dd($results);
        $albums = $results->photosets['photoset'];

        $data['metadata'] = [
            'stat' => $results->stat,
            'page' => $results->photosets['page'],
            'pages' => $results->photosets['pages'],
            'per_page' => $results->photosets['perpage'],
            'total' => $results->photosets['total'],
        ];
        $data['albums'] = $albums;
        return view('welcome')
         ->with('data', $data);
    }
}
```

any suggestions? :)

**Comment by mpixelz** [comment]
also if there is some way to cache the images instead of requesting each time.. much appreciated :)
thanks.

**Comment by Jeroen-G** [comment]
Try replacing `env('FLICKR_KEY', '')` with `env('FLICKR_KEY')` so there is no default of no key. Or put in your key directly in that place to see if the error lies with Flickr or Laravel or somewhere else.

Regarding caching: I suppose you can cache with Laravel's system.

**Comment by mpixelz** [comment]
Just tried both ways and still the error is the same.

```
Response {#601 ▼
  #contents: array:3 [▼
    "stat" => "fail"
    "code" => 100
    "message" => "Invalid API Key (Key has invalid format)"
  ]
}
```

**Comment by Jeroen-G** [comment]
A quick Google search said something about a api key auth signature. I'll have to play with the issue to see what is happening when I have time. Maybe you can do too. For example with a new key, other functions and calls, etc.

**Comment by Jeroen-G** [comment]
Everything works for me in the way you set it up. Also after a `artisan cache:clear`

**Comment by peterpeerdeman** [comment]
Hi there,

I had the same problem as @mpixelz and was dumbfounded as to what te solution should be. After some fiddling around I found it out.

The problem did not occur locally, I could only reproduce it on my server environment. The problem was that the method `env('ENV_VARIABLE_NAME')` does not properly work (and is not intended to work properly) outside the config files in laravel.

@mpixelz, the code you posted in this example is loading the env variable directly into your laravel code (the same way I did in my code), but you should only call the env method inside the config files and use e.g. `config('app.timezone')` (or in our case `config('flickr.key')` and create a file `config/flickr.php` with a `key` value in the array) when loading variables. This paragraph in the laravel documentation describes it in more detail: https://laravel.com/docs/5.4/configuration#accessing-configuration-values

After I switched to this way of loading the flickr API key, I had no problems anymore, it had nothing to do with @Jeroen-G's excellent Flickr module (thank you btw for creating this!)

**Comment by Jeroen-G** [comment]
Thank you for your solution!

**Comment by harishletsgo** [comment]
Any ideas for caching the requests?

**Comment by Jeroen-G** [comment]
Take a look at Laravel's own caching, I think you could use that. If you run into issues with that, feel free to open a new issue.
